// Generated by Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)
#ifndef HHSDKVIDEO_SWIFT_H
#define HHSDKVIDEO_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFoundation;
@import CoreFoundation;
@import CoreGraphics;
@import CoreLocation;
@import CoreMedia;
@import Foundation;
@import ObjectiveC;
@import Photos;
@import QuartzCore;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="HHSDKVideo",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif






@class NSNumber;
@class NSString;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC10HHSDKVideo13CommentBaseVC")
@interface CommentBaseVC : UIViewController
- (void)viewWillAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10HHSDKVideo9CommentVC")
@interface CommentVC : CommentBaseVC
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10HHSDKVideo33DGElasticPullToRefreshLoadingView")
@interface DGElasticPullToRefreshLoadingView : UIView
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10HHSDKVideo39DGElasticPullToRefreshLoadingViewCircle")
@interface DGElasticPullToRefreshLoadingViewCircle : DGElasticPullToRefreshLoadingView
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)tintColorDidChange;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10HHSDKVideo26DGElasticPullToRefreshView")
@interface DGElasticPullToRefreshView : UIView
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)change context:(void * _Nullable)context;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end




SWIFT_CLASS("_TtC10HHSDKVideo26EKAccessoryNoteMessageView")
@interface EKAccessoryNoteMessageView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITraitCollection;

SWIFT_CLASS("_TtC10HHSDKVideo19EKSimpleMessageView")
@interface EKSimpleMessageView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)traitCollectionDidChange:(UITraitCollection * _Nullable)previousTraitCollection;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10HHSDKVideo18EKAlertMessageView")
@interface EKAlertMessageView : EKSimpleMessageView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


/// Dynamic button bar view
/// Buttons are set according to the received content.
/// 1-2 buttons spread horizontally
/// 3 or more buttons spread vertically
SWIFT_CLASS("_TtC10HHSDKVideo15EKButtonBarView")
@interface EKButtonBarView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (void)traitCollectionDidChange:(UITraitCollection * _Nullable)previousTraitCollection;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10HHSDKVideo17EKFormMessageView")
@interface EKFormMessageView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)traitCollectionDidChange:(UITraitCollection * _Nullable)previousTraitCollection;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10HHSDKVideo22EKImageNoteMessageView")
@interface EKImageNoteMessageView : EKAccessoryNoteMessageView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10HHSDKVideo20EKMessageContentView")
@interface EKMessageContentView : UIView
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)traitCollectionDidChange:(UITraitCollection * _Nullable)previousTraitCollection;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10HHSDKVideo17EKNoteMessageView")
@interface EKNoteMessageView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10HHSDKVideo25EKNotificationMessageView")
@interface EKNotificationMessageView : EKSimpleMessageView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)traitCollectionDidChange:(UITraitCollection * _Nullable)previousTraitCollection;
@end


SWIFT_CLASS("_TtC10HHSDKVideo18EKPopUpMessageView")
@interface EKPopUpMessageView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)traitCollectionDidChange:(UITraitCollection * _Nullable)previousTraitCollection;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10HHSDKVideo27EKProcessingNoteMessageView")
@interface EKProcessingNoteMessageView : EKAccessoryNoteMessageView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10HHSDKVideo19EKRatingMessageView")
@interface EKRatingMessageView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10HHSDKVideo18EKRatingSymbolView")
@interface EKRatingSymbolView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10HHSDKVideo28EKRatingSymbolsContainerView")
@interface EKRatingSymbolsContainerView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10HHSDKVideo11EKTextField")
@interface EKTextField : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)traitCollectionDidChange:(UITraitCollection * _Nullable)previousTraitCollection;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10HHSDKVideo23EKXStatusBarMessageView")
@interface EKXStatusBarMessageView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end



SWIFT_CLASS("_TtC10HHSDKVideo18HHAppProtocolCheck")
@interface HHAppProtocolCheck : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UITextView;
@class NSURL;

@interface HHAppProtocolCheck (SWIFT_EXTENSION(HHSDKVideo)) <UITextViewDelegate>
- (BOOL)textView:(UITextView * _Nonnull)textView shouldInteractWithURL:(NSURL * _Nonnull)URL inRange:(NSRange)characterRange interaction:(UITextItemInteraction)interaction SWIFT_WARN_UNUSED_RESULT;
@end

/// 接通前的呼叫状态
/// <ul>
///   <li>
///     onStart: 呼叫开始
///   </li>
///   <li>
///     waitingDoctor: 等待空闲的医生
///   </li>
///   <li>
///     callFreeDoctor: 有医生空闲，开始呼叫
///   </li>
///   <li>
///     callConnect: 建立呼叫
///   </li>
///   <li>
///     didRing: 医生响铃，等待接受
///   </li>
/// </ul>
typedef SWIFT_ENUM(NSInteger, HHBaseCallingState, open) {
  HHBaseCallingStateOnStart = 0,
  HHBaseCallingStateWaitingDoctor = 1,
  HHBaseCallingStateCallFreeDoctor = 2,
  HHBaseCallingStateCallConnect = 3,
  HHBaseCallingStateDidRing = 4,
};

typedef SWIFT_ENUM(NSInteger, HHBasePermissionType, open) {
  HHBasePermissionTypeLocationAlways = 0,
  HHBasePermissionTypeLocationWhenInUse = 1,
  HHBasePermissionTypeMicrophone = 2,
  HHBasePermissionTypeCamera = 3,
  HHBasePermissionTypePhotos = 4,
};


SWIFT_CLASS("_TtC10HHSDKVideo9HHBaseSDK")
@interface HHBaseSDK : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=default) HHBaseSDK * _Nonnull default_;)
+ (HHBaseSDK * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
/// SDK init
- (void)start;
/// 登录账户
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     userToken: 用户的唯一标志
///   </li>
///   <li>
///     completion: 完成的回调
///   </li>
/// </ul>
- (void)loginWithUserToken:(NSString * _Nonnull)userToken completion:(void (^ _Nonnull)(NSString * _Nullable))completion;
/// 登出
/// \param callback 登出回调(字符串为空表示成功)
///
- (void)logout:(void (^ _Nullable)(NSString * _Nullable))callback;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// 视频管理器代理
SWIFT_PROTOCOL("_TtP10HHSDKVideo19HHBaseVideoDelegate_")
@protocol HHBaseVideoDelegate <NSObject>
/// 主动视频时的呼叫状态变化
/// \param state 当前呼叫状态
///
- (void)callStateChange:(enum HHBaseCallingState)state;
@optional
/// \param orderId 当前订单ID
///
- (void)onStartWithOrderId:(NSString * _Nullable)orderId;
@required
/// 通话已接通
- (void)callDidEstablish;
/// 视频页面回调
- (void)getChatParentView:(UIView * _Nonnull)view;
/// 呼叫失败(业务服务报错)
- (void)callFailWithCode:(NSInteger)code error:(NSString * _Nonnull)error;
/// 呼叫失败（音视频服务报错）
/// \param error 错误信息
///
- (void)onFail:(NSInteger)errorCode errrorStr:(NSString * _Nullable)errrorStr;
- (void)onCancel;
/// 呼叫时获取到订单信息
- (void)receivedOrder:(NSString * _Nonnull)orderId;
/// 通话已结束 (接通之后才有结束)
- (void)callDidFinish;
/// 转呼医生
- (void)onExtensionDoctor;
/// 接收到呼叫(被呼叫方)
/// \param callID 呼叫的 id
///
- (void)onReceive:(NSString * _Nonnull)callID;
/// 收到视频呼入时的操作（被呼叫方）
/// \param accept 接受或者拒接
///
- (void)onResponse:(BOOL)accept;
/// 缺少必要权限
/// \param type 缺少的权限类型
///
- (void)onLeakPermission:(enum HHBasePermissionType)type;
@optional
/// 强制下线
- (void)onForceOffline;
/// 视频中邀请家人
- (void)inviteFamily:(NSString * _Nonnull)page;
/// 去支付次卡
- (void)goPayCount:(NSString * _Nonnull)url;
@end


SWIFT_PROTOCOL("_TtP10HHSDKVideo14HHCallDelegate_")
@protocol HHCallDelegate <NSObject>
@optional
/// 呼叫状态
/// \param error 错误信息(为空表示呼叫成功)
///
- (void)onCallStatus:(NSError * _Nullable)error;
/// 呼叫成功
- (void)onCallSuccess;
/// 呼叫完成
- (void)callFinished;
@end

/// 呼叫类型
/// <ul>
///   <li>
///     child: 儿童
///   </li>
///   <li>
///     adult: 成人
///   </li>
/// </ul>
typedef SWIFT_ENUM(NSInteger, HHCallType, open) {
  HHCallTypeChild = 600000,
  HHCallTypeAdult = 600002,
};


/// 用户信息
SWIFT_CLASS("_TtC10HHSDKVideo12HHCallerInfo")
@interface HHCallerInfo : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10HHSDKVideo11HHDateUtils")
@interface HHDateUtils : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end





SWIFT_CLASS("_TtC10HHSDKVideo15HHDeviceManager")
@interface HHDeviceManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10HHSDKVideo18HHFileCacheManager")
@interface HHFileCacheManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_PROTOCOL("_TtP10HHSDKVideo4HHIM_")
@protocol HHIM
- (void)register:(NSString * _Nullable)cerName;
- (void)login:(void (^ _Nullable)(NSString * _Nullable))completion;
- (void)autoLogin:(void (^ _Nullable)(NSString * _Nullable))completion;
- (void)logout:(void (^ _Nullable)(NSString * _Nullable))callback;
- (BOOL)canVideo SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, HHLogMode, open) {
/// nothing show
  HHLogModeError = 0,
  HHLogModeWarn = 1,
/// only information
  HHLogModeInfo = 2,
/// network info
  HHLogModeDebug = 3,
/// debug mode
  HHLogModeVerbose = 4,
};


SWIFT_CLASS("_TtC10HHSDKVideo23HHMediaStatusCheckUtils")
@interface HHMediaStatusCheckUtils : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10HHSDKVideo18HHMedicNetObserver")
@interface HHMedicNetObserver : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10HHSDKVideo18HHNeedRealNameView")
@interface HHNeedRealNameView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end


@class UIWindow;
@class UICollectionView;
@class NSIndexPath;
@class UICollectionViewCell;
@class UIScrollView;

IB_DESIGNABLE
SWIFT_CLASS("_TtC10HHSDKVideo11HHPagerView")
@interface HHPagerView : UIView <UICollectionViewDataSource, UICollectionViewDelegate>
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (void)willMoveToWindow:(UIWindow * _Nullable)newWindow;
- (void)prepareForInterfaceBuilder;
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView * _Nonnull)collectionView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView shouldHighlightItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didHighlightItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView shouldSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView willDisplayCell:(UICollectionViewCell * _Nonnull)cell forItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didEndDisplayingCell:(UICollectionViewCell * _Nonnull)cell forItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewWillBeginDragging:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewWillEndDragging:(UIScrollView * _Nonnull)scrollView withVelocity:(CGPoint)velocity targetContentOffset:(CGPoint * _Nonnull)targetContentOffset;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndScrollingAnimation:(UIScrollView * _Nonnull)scrollView;
@end

typedef SWIFT_ENUM(NSInteger, HHPagerViewTransformerType, open) {
  HHPagerViewTransformerTypeCrossFading = 0,
  HHPagerViewTransformerTypeZoomOut = 1,
  HHPagerViewTransformerTypeDepth = 2,
  HHPagerViewTransformerTypeOverlap = 3,
  HHPagerViewTransformerTypeLinear = 4,
  HHPagerViewTransformerTypeCoverFlow = 5,
  HHPagerViewTransformerTypeFerrisWheel = 6,
  HHPagerViewTransformerTypeInvertedFerrisWheel = 7,
  HHPagerViewTransformerTypeCubic = 8,
};


SWIFT_CLASS("_TtC10HHSDKVideo12HHPermission")
@interface HHPermission : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class CLLocationManager;

@interface HHPermission (SWIFT_EXTENSION(HHSDKVideo)) <CLLocationManagerDelegate>
- (void)locationManager:(CLLocationManager * _Nonnull)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status;
@end







@interface HHPermission (SWIFT_EXTENSION(HHSDKVideo))
/// The textual representation of self.
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
/// A textual representation of this instance, suitable for debugging.
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
@end


SWIFT_CLASS("_TtC10HHSDKVideo18HHPhotoConfigModel")
@interface HHPhotoConfigModel : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10HHSDKVideo23HHPhotoPickerController")
@interface HHPhotoPickerController : UINavigationController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNavigationBarClass:(Class _Nullable)navigationBarClass toolbarClass:(Class _Nullable)toolbarClass OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=5.0);
- (nonnull instancetype)initWithRootViewController:(UIViewController * _Nonnull)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10HHSDKVideo20HHPhotoPickerManager")
@interface HHPhotoPickerManager : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10HHSDKVideo18HHPhotoPickerModel")
@interface HHPhotoPickerModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIColor;

SWIFT_CLASS("_TtC10HHSDKVideo20HHPhotoUIConfigModel")
@interface HHPhotoUIConfigModel : NSObject
@property (nonatomic, strong) UIColor * _Nonnull indexLabelBgColor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;

/// 音视频回调
SWIFT_PROTOCOL("_TtP10HHSDKVideo5HHRTC_")
@protocol HHRTC
@optional
- (void)setRoomIdWithRoomId:(NSString * _Nonnull)roomId;
- (void)setOrderIdWithOrderId:(NSString * _Nonnull)orderId;
/// 开始呼叫
- (void)startCallWithCallee:(NSString * _Nonnull)callee orderId:(NSString * _Nullable)orderId;
/// 进房
- (void)enterRoomWithOrderId:(NSString * _Nonnull)orderId roomId:(NSString * _Nonnull)roomId;
/// 切换本地音频采集
- (void)switchLocalAudio:(BOOL)isOpen;
/// 切换本地音频采集
- (void)switchLocalVideo:(BOOL)isOpen localView:(UIView * _Nonnull)localView;
/// 开启医生视频
- (void)openDoctorViewWithUserId:(NSString * _Nonnull)userId view:(UIView * _Nonnull)view;
/// 关闭医生视频
- (void)closeDoctorViewWithUserId:(NSString * _Nonnull)userId;
/// 切换摄像头
- (void)switchCamera:(BOOL)isFront;
/// 设置闪光灯
- (void)switchCameraFlash:(BOOL)isOpen;
/// 发送房间消息或p2p消息
- (void)sendMsgWithIsSignal:(BOOL)isSignal cmd:(NSString * _Nonnull)cmd to:(NSString * _Nonnull)to complete:(void (^ _Nullable)(NSString * _Nullable))complete;
/// 退房
- (void)leaveRoom;
/// 挂断
- (void)hangUpWithCallId:(uint64_t)callId;
/// 开始响铃
- (void)startRingWithAudioId:(NSInteger)audioId;
/// 结束响铃
- (void)stopRing;
- (void)snapshotVideoWithUserId:(NSString * _Nullable)userId imageBack:(void (^ _Nonnull)(UIImage * _Nonnull))imageBack;
@end

@class UITextField;

SWIFT_CLASS("_TtC10HHSDKVideo22HHRealNameInputNewView")
@interface HHRealNameInputNewView : UIView
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified idCardTF;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface HHRealNameInputNewView (SWIFT_EXTENSION(HHSDKVideo)) <UITextFieldDelegate>
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (void)textFieldDidBeginEditing:(UITextField * _Nonnull)textField;
@end



SWIFT_CLASS("_TtC10HHSDKVideo19HHRealNameInputView")
@interface HHRealNameInputView : UIView
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



@interface HHRealNameInputView (SWIFT_EXTENSION(HHSDKVideo)) <UITextFieldDelegate>
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
@end


typedef SWIFT_ENUM(NSInteger, HHRealNameType, open) {
  HHRealNameTypeNormal = 0,
  HHRealNameTypeBuyMedic = 1,
};


SWIFT_CLASS("_TtC10HHSDKVideo12HHRealNameVC")
@interface HHRealNameVC : UIViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end




/// 基础全局配置
SWIFT_CLASS("_TtC10HHSDKVideo16HHSDKBaseOptions")
@interface HHSDKBaseOptions : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=default) HHSDKBaseOptions * _Nonnull default_;)
+ (HHSDKBaseOptions * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
/// 是否是SDK
@property (nonatomic) BOOL isSDK;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10HHSDKVideo16HHTRTCVolumeInfo")
@interface HHTRTCVolumeInfo : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// 加载进度协议
SWIFT_PROTOCOL("_TtP10HHSDKVideo14HHVideoHUDable_")
@protocol HHVideoHUDable
/// 显示加载中
- (void)showHUD;
/// 隐藏菊花
- (void)dismissHUD;
/// 正确提示
- (void)showSuccess:(NSString * _Nullable)message;
/// 错误提示
- (void)showError:(NSString * _Nullable)messgae;
@end


/// HH 定位
SWIFT_CLASS("_TtC10HHSDKVideo15HHVideoLocation")
@interface HHVideoLocation : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=default) HHVideoLocation * _Nonnull default_;)
+ (HHVideoLocation * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
/// 启用定位
/// \param lng 经度
///
/// \param lat 纬度
///
- (void)startLocationWithLng:(NSString * _Nonnull)lng lat:(NSString * _Nonnull)lat;
/// 关闭定位
- (void)closeLocation;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol OptionProtocal;

SWIFT_CLASS("_TtC10HHSDKVideo10HHVideoSDK")
@interface HHVideoSDK : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=default) HHVideoSDK * _Nonnull default_;)
+ (HHVideoSDK * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) void (^ _Nullable photosPreview)(NSArray<NSString *> * _Nonnull);
@property (nonatomic, readonly) BOOL isLogined;
/// 初始化 SDK
/// \param option 可选的 SDK 配置
///
- (void)startWithOption:(id <OptionProtocal> _Nonnull)option im:(id <HHIM> _Nonnull)im rtc:(id <HHRTC> _Nonnull)rtc;
/// 登录账户
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     userToken: 用户的唯一标志
///   </li>
///   <li>
///     completion: 完成的回调
///   </li>
/// </ul>
- (void)loginWithUserToken:(NSString * _Nonnull)userToken completion:(void (^ _Nonnull)(NSString * _Nullable))completion;
/// 自动登录(如果已经保存了用户帐号和令牌,建议使用这个登录方式)
/// \param uuid 自动登录参数
///
- (void)autoLoginWithUuid:(NSInteger)uuid completion:(void (^ _Nonnull)(NSString * _Nullable))completion;
/// 登出
/// \param callback 登出回调(字符串为空表示成功)
///
- (void)logout:(void (^ _Nullable)(NSString * _Nullable))callback;
- (void)terminate;
/// 设置支付宝支付回调
- (void)setAlipayHookWithAlipayCallback:(BOOL (^ _Nonnull)(NSString * _Nonnull, NSString * _Nonnull, void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nonnull)))alipayCallback;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface HHVideoSDK (SWIFT_EXTENSION(HHSDKVideo))
- (void)onKickedOffline;
@end



@interface HHVideoSDK (SWIFT_EXTENSION(HHSDKVideo))
/// 三方登录
/// \param userToken 三方信息
///
/// \param completion 完成的回调
///
- (void)loginForThirdId:(NSDictionary<NSString *, id> * _Nonnull)thirdInfo completion:(void (^ _Nonnull)(NSString * _Nullable))completion;
@end




@interface HHVideoSDK (SWIFT_EXTENSION(HHSDKVideo))
/// 跳转信息流首页
- (void)skipChatHomeWithIsByPresent:(BOOL)isByPresent vc:(UIViewController * _Nullable)vc;
- (void)skipChatHome:(UINavigationController * _Nonnull)nav;
- (UIViewController * _Nullable)chatHomeVC SWIFT_WARN_UNUSED_RESULT;
@end


@interface HHVideoSDK (SWIFT_EXTENSION(HHSDKVideo))
/// 指定人发起呼叫(带 UI)
/// <ul>
///   <li>
///     Parameters:
///   </li>
/// </ul>
- (void)startMemberCallWithNeedSelectMember:(BOOL)needSelectMember;
@end



@interface HHVideoSDK (SWIFT_EXTENSION(HHSDKVideo))
/// 指定人呼叫
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     userToken: 呼叫人userToken
///   </li>
/// </ul>
- (void)call:(NSString * _Nonnull)memberToken scene:(NSString * _Nullable)scene;
@end


@interface HHVideoSDK (SWIFT_EXTENSION(HHSDKVideo))
/// 主动发起多人通话
/// \param type 呼叫类型
///
/// \param callee 被呼叫人的信息
///
- (void)startTeamCall:(enum HHCallType)type callee:(HHCallerInfo * _Nonnull)callee callDelegate:(id <HHCallDelegate> _Nullable)callDelegate;
@end


@interface HHVideoSDK (SWIFT_EXTENSION(HHSDKVideo))
/// 获取病历详情
/// \param userToken 当前人的唯一标志
///
/// \param medicId 病历id
///
///
/// returns:
/// url
- (NSString * _Nonnull)getMedicDetailWithUserToken:(NSString * _Nonnull)userToken medicId:(NSString * _Nonnull)medicId SWIFT_WARN_UNUSED_RESULT;
/// 获取病历列表
/// \param userToken 当前人的唯一标志
///
///
/// returns:
/// url
- (NSString * _Nonnull)getMedicListWithUserToken:(NSString * _Nonnull)userToken SWIFT_WARN_UNUSED_RESULT;
/// 获取所有病历列表
/// \param userToken 主账户的唯一标志
///
///
/// returns:
/// url
- (NSString * _Nonnull)getAllMedicsWithUserToken:(NSString * _Nonnull)userToken SWIFT_WARN_UNUSED_RESULT;
@end


@interface HHVideoSDK (SWIFT_EXTENSION(HHSDKVideo))
/// 呼叫
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     type: 呼叫类型
///   </li>
///   <li>
///     callDelegate: 呼叫状态回调
///   </li>
/// </ul>
- (void)startCall:(enum HHCallType)type scene:(NSString * _Nullable)scene callDelegate:(id <HHCallDelegate> _Nullable)callDelegate;
- (void)startNewCall:(NSInteger)uuid type:(enum HHCallType)type callDelegate:(id <HHCallDelegate> _Nullable)callDelegate;
/// 指定人呼叫
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     uuid: 呼叫人Uuid
///   </li>
///   <li>
///     callDelegate: 呼叫状态回调
///   </li>
/// </ul>
- (void)startCall:(NSInteger)uuid scene:(NSString * _Nullable)scene type:(enum HHCallType)type callDelegate:(id <HHCallDelegate> _Nullable)callDelegate;
@end


SWIFT_PROTOCOL("_TtP10HHSDKVideo22MessageOptionsProtocol_")
@protocol MessageOptionsProtocol
/// 是否是Present显示
@property (nonatomic) BOOL isByPresent;
/// 信息流是否过滤医生总结
@property (nonatomic) BOOL isFilterSummary SWIFT_DEPRECATED_MSG("已弃用，如有问题，请联系和缓");
/// 信息流是否过滤药卡
@property (nonatomic) BOOL isFilterMedicinal SWIFT_DEPRECATED_MSG("已弃用，如有问题，请联系和缓");
/// 信息流默认头像
@property (nonatomic, copy) NSString * _Nonnull defaultDocHeader;
/// 信息流默认昵称
@property (nonatomic, copy) NSString * _Nonnull defaultDocName;
/// 信息流默认标题
@property (nonatomic, copy) NSString * _Nonnull messageTitle;
@end






@protocol VideoOptionsProtocol;
@protocol UsercenterOptionsProtocol;

SWIFT_PROTOCOL("_TtP10HHSDKVideo14OptionProtocal_")
@protocol OptionProtocal
@property (nonatomic) BOOL isDebug;
@property (nonatomic) BOOL isDevelopment;
/// 加载进度自定义
@property (nonatomic, strong) id <HHVideoHUDable> _Nonnull pHudManager;
@property (nonatomic, copy) NSString * _Nonnull productId;
@property (nonatomic, copy) NSString * _Nullable cerName;
@property (nonatomic) enum HHLogMode logLevel;
@property (nonatomic, copy) NSString * _Nonnull mExtension;
@property (nonatomic) NSInteger changeDoctorTime;
/// 日志回调(仅测试有用)
@property (nonatomic, copy) void (^ _Nullable logCallback)(NSString * _Nonnull);
@property (nonatomic, strong) id <VideoOptionsProtocol> _Nonnull pVideoOptions;
@property (nonatomic, strong) id <MessageOptionsProtocol> _Nonnull pMessageOptions;
@property (nonatomic, strong) id <UsercenterOptionsProtocol> _Nonnull pUserCenterOptions;
@property (nonatomic, copy) NSString * _Nonnull sdkVersion;
@property (nonatomic, copy) NSString * _Nonnull appVersion;
@property (nonatomic) BOOL isTRTC;
@property (nonatomic) BOOL needDNS;
@property (nonatomic) BOOL shouldWaingCall;
- (void)setUserExtensionWithUserExtension:(NSString * _Nonnull)userExtension;
- (void)setCallExtensionWithCallExtension:(NSString * _Nonnull)callExtension;
@end










































@class UITapGestureRecognizer;
@class NSTimer;

@interface UIView (SWIFT_EXTENSION(HHSDKVideo))
- (void)hhhandleToastTapped:(UITapGestureRecognizer * _Nonnull)recognizer;
- (void)hhtoastTimerDidFinish:(NSTimer * _Nonnull)timer;
@end




@interface UIViewController (SWIFT_EXTENSION(HHSDKVideo))
- (void)hhCloseThisController;
- (void)hhPopThisController;
@end




SWIFT_PROTOCOL("_TtP10HHSDKVideo25UsercenterOptionsProtocol_")
@protocol UsercenterOptionsProtocol
/// 是否隐藏会员信息
@property (nonatomic) BOOL enableVipInfo;
/// 是否隐藏个人中心入口
@property (nonatomic) BOOL hideUserCenter;
/// 是否展示激活码入口
@property (nonatomic) BOOL enableActivate;
/// 是否展示档案库入口
@property (nonatomic) BOOL enableMedical;
/// 档案库是否可以增加成员
@property (nonatomic) BOOL enableAddMemberInDoc;
@property (nonatomic) BOOL enableBuyService;
/// 是否允许弹出实名认证
@property (nonatomic) BOOL enablePopRealName;
/// 是否隐藏权益列表
@property (nonatomic) BOOL isCloseMoreFunc;
@end


SWIFT_CLASS("_TtC10HHSDKVideo9VCManager")
@interface VCManager : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end






SWIFT_PROTOCOL("_TtP10HHSDKVideo20VideoOptionsProtocol_")
@protocol VideoOptionsProtocol
/// 呼叫时是否需要过滤生日性别 <解放行不需要加>
@property (nonatomic) BOOL filterCallerInfo;
/// 是否开启美颜
@property (nonatomic) BOOL allowBeauty;
/// 允许视频完成后评价
@property (nonatomic) BOOL allowEvaluate;
/// 选人页面是否显示增加成员入口
@property (nonatomic) BOOL allowAddMember;
/// 选人页面是否可以选择多人视频
@property (nonatomic) BOOL allowMulti;
/// 呼叫扩展参数
@property (nonatomic, copy) NSString * _Nonnull mCallExtension;
/// 是否显示医生信息
@property (nonatomic) BOOL isShowDocInfo;
/// 可以关闭摄像头
@property (nonatomic) BOOL enableCloseCamera;
/// 不可关闭摄像头
@property (nonatomic) BOOL isCloseCameraCall;
/// 关闭视频中实名
@property (nonatomic) BOOL isCloseRealNameInVideo;
/// 显示视频中邀请家人
@property (nonatomic) BOOL showInviteInVideo;
@end


SWIFT_CLASS("_TtC10HHSDKVideo16ZLAlbumListModel")
@interface ZLAlbumListModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


enum CaptureSessionPreset : NSInteger;
enum FocusMode : NSInteger;
enum ExposureMode : NSInteger;
enum FlashMode : NSInteger;
enum VideoExportType : NSInteger;

SWIFT_CLASS("_TtC10HHSDKVideo21ZLCameraConfiguration")
@interface ZLCameraConfiguration : NSObject
/// Video resolution. Defaults to hd1280x720.
@property (nonatomic) enum CaptureSessionPreset sessionPreset;
/// Camera focus mode. Defaults to continuousAutoFocus
@property (nonatomic) enum FocusMode focusMode;
/// Camera exposure mode. Defaults to continuousAutoExposure
@property (nonatomic) enum ExposureMode exposureMode;
/// Camera flahs mode. Default is off. Defaults to off.
@property (nonatomic) enum FlashMode flashMode;
/// Video export format for recording video and editing video. Defaults to mov.
@property (nonatomic) enum VideoExportType videoExportType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, CaptureSessionPreset, open) {
  CaptureSessionPresetCif352x288 = 0,
  CaptureSessionPresetVga640x480 = 1,
  CaptureSessionPresetHd1280x720 = 2,
  CaptureSessionPresetHd1920x1080 = 3,
  CaptureSessionPresetHd4K3840x2160 = 4,
};

typedef SWIFT_ENUM(NSInteger, FocusMode, open) {
  FocusModeAutoFocus = 0,
  FocusModeContinuousAutoFocus = 1,
};

typedef SWIFT_ENUM(NSInteger, ExposureMode, open) {
  ExposureModeAutoExpose = 0,
  ExposureModeContinuousAutoExposure = 1,
};

typedef SWIFT_ENUM(NSInteger, FlashMode, open) {
  FlashModeAuto = 0,
  FlashModeOn = 1,
  FlashModeOff = 2,
};

typedef SWIFT_ENUM(NSInteger, VideoExportType, open) {
  VideoExportTypeMov = 0,
  VideoExportTypeMp4 = 1,
};


@class CAAnimation;

SWIFT_CLASS("_TtC10HHSDKVideo14ZLCustomCamera")
@interface ZLCustomCamera : UIViewController <CAAnimationDelegate>
@property (nonatomic, copy) void (^ _Nullable takeDoneBlock)(UIImage * _Nullable, NSURL * _Nullable);
@property (nonatomic, copy) void (^ _Nullable cancelBlock)(void);
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)viewDidLayoutSubviews;
- (void)animationDidStop:(CAAnimation * _Nonnull)anim finished:(BOOL)flag;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@class UIGestureRecognizer;

@interface ZLCustomCamera (SWIFT_EXTENSION(HHSDKVideo)) <UIGestureRecognizerDelegate>
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer * _Nonnull)otherGestureRecognizer SWIFT_WARN_UNUSED_RESULT;
@end

@class AVCaptureFileOutput;
@class AVCaptureConnection;

@interface ZLCustomCamera (SWIFT_EXTENSION(HHSDKVideo)) <AVCaptureFileOutputRecordingDelegate>
- (void)captureOutput:(AVCaptureFileOutput * _Nonnull)output didStartRecordingToOutputFileAtURL:(NSURL * _Nonnull)fileURL fromConnections:(NSArray<AVCaptureConnection *> * _Nonnull)connections;
- (void)captureOutput:(AVCaptureFileOutput * _Nonnull)output didFinishRecordingToOutputFileAtURL:(NSURL * _Nonnull)outputFileURL fromConnections:(NSArray<AVCaptureConnection *> * _Nonnull)connections error:(NSError * _Nullable)error;
@end

@class AVCapturePhotoOutput;
@class AVCaptureResolvedPhotoSettings;
@class AVCaptureBracketedStillImageSettings;

@interface ZLCustomCamera (SWIFT_EXTENSION(HHSDKVideo)) <AVCapturePhotoCaptureDelegate>
- (void)captureOutput:(AVCapturePhotoOutput * _Nonnull)output willCapturePhotoForResolvedSettings:(AVCaptureResolvedPhotoSettings * _Nonnull)resolvedSettings;
- (void)captureOutput:(AVCapturePhotoOutput * _Nonnull)output didFinishProcessingPhotoSampleBuffer:(CMSampleBufferRef _Nullable)photoSampleBuffer previewPhotoSampleBuffer:(CMSampleBufferRef _Nullable)previewPhotoSampleBuffer resolvedSettings:(AVCaptureResolvedPhotoSettings * _Nonnull)resolvedSettings bracketSettings:(AVCaptureBracketedStillImageSettings * _Nullable)bracketSettings error:(NSError * _Nullable)error;
@end


SWIFT_CLASS("_TtC10HHSDKVideo10ZLDrawPath")
@interface ZLDrawPath : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class ZLImageClipRatio;
@class ZLFilter;
@protocol ZLImageStickerContainerDelegate;

SWIFT_CLASS("_TtC10HHSDKVideo24ZLEditImageConfiguration")
@interface ZLEditImageConfiguration : NSObject
/// Edit image tools.  (This property is only for objc).
/// warning:
/// If you want to use the image sticker feature, you must provide a view that implements ZLImageStickerContainerDelegate.
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull tools_objc;
/// Draw colors for image editor.
@property (nonatomic, copy) NSArray<UIColor *> * _Nonnull drawColors;
/// The default draw color. If this color not in editImageDrawColors, will pick the first color in editImageDrawColors as the default.
@property (nonatomic, strong) UIColor * _Nonnull defaultDrawColor;
/// Edit ratios for image editor.
@property (nonatomic, copy) NSArray<ZLImageClipRatio *> * _Nonnull clipRatios;
/// Text sticker colors for image editor.
@property (nonatomic, copy) NSArray<UIColor *> * _Nonnull textStickerTextColors;
/// The default text sticker color. If this color not in textStickerTextColors, will pick the first color in textStickerTextColors as the default.
@property (nonatomic, strong) UIColor * _Nonnull textStickerDefaultTextColor;
/// Filters for image editor.
@property (nonatomic, copy) NSArray<ZLFilter *> * _Nonnull filters;
@property (nonatomic, strong) UIView <ZLImageStickerContainerDelegate> * _Nullable imageStickerContainerView;
/// Adjust image tools.  (This property is only for objc).
/// Valid when the tools contain EditTool.adjust
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull adjustTools_objc;
/// Give an impact feedback when the adjust slider value is zero. Defaults to true.
@property (nonatomic) BOOL impactFeedbackWhenAdjustSliderValueIsZero;
/// Impact feedback style. Defaults to .medium
@property (nonatomic) UIImpactFeedbackStyle impactFeedbackStyle;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, EditTool, open) {
  EditToolDraw = 0,
  EditToolClip = 1,
  EditToolImageSticker = 2,
  EditToolTextSticker = 3,
  EditToolMosaic = 4,
  EditToolFilter = 5,
  EditToolAdjust = 6,
};

typedef SWIFT_ENUM(NSInteger, AdjustTool, open) {
  AdjustToolBrightness = 0,
  AdjustToolContrast = 1,
  AdjustToolSaturation = 2,
};



SWIFT_CLASS("_TtC10HHSDKVideo16ZLEditImageModel")
@interface ZLEditImageModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class ZLEnlargeButton;
@class CAGradientLayer;
@class UIButton;
@class UIImageView;

SWIFT_CLASS("_TtC10HHSDKVideo25ZLEditImageViewController")
@interface ZLEditImageViewController : UIViewController
@property (nonatomic) CGFloat drawColViewH;
@property (nonatomic) CGFloat filterColViewH;
@property (nonatomic) CGFloat adjustColViewH;
@property (nonatomic, strong) UIColor * _Nonnull ashbinNormalBgColor;
@property (nonatomic, strong) ZLEnlargeButton * _Nonnull cancelBtn;
@property (nonatomic, strong) UIScrollView * _Nonnull mainScrollView;
@property (nonatomic, strong) UIView * _Nonnull topShadowView;
@property (nonatomic, strong) CAGradientLayer * _Nonnull topShadowLayer;
@property (nonatomic, strong) UIView * _Nonnull bottomShadowView;
@property (nonatomic, strong) CAGradientLayer * _Nonnull bottomShadowLayer;
@property (nonatomic, strong) UIButton * _Nonnull doneBtn;
@property (nonatomic, strong) UIButton * _Nonnull revokeBtn;
@property (nonatomic, strong) UIView * _Nonnull ashbinView;
@property (nonatomic, strong) UIImageView * _Nonnull ashbinImgView;
@property (nonatomic) CGFloat drawLineWidth;
@property (nonatomic) CGFloat mosaicLineWidth;
@property (nonatomic, copy) void (^ _Nullable editFinishBlock)(UIImage * _Nonnull, ZLEditImageModel * _Nullable);
@property (nonatomic, copy) void (^ _Nullable cancelEditBlock)(void);
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
+ (void)showEditImageVCWithParentVC:(UIViewController * _Nullable)parentVC animate:(BOOL)animate image:(UIImage * _Nonnull)image editModel:(ZLEditImageModel * _Nullable)editModel cancel:(void (^ _Nullable)(void))cancel completion:(void (^ _Nullable)(UIImage * _Nonnull, ZLEditImageModel * _Nullable))completion;
- (nonnull instancetype)initWithImage:(UIImage * _Nonnull)image editModel:(ZLEditImageModel * _Nullable)editModel OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@interface ZLEditImageViewController (SWIFT_EXTENSION(HHSDKVideo)) <UIGestureRecognizerDelegate>
- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer * _Nonnull)gestureRecognizer SWIFT_WARN_UNUSED_RESULT;
@end


@interface ZLEditImageViewController (SWIFT_EXTENSION(HHSDKVideo)) <UICollectionViewDataSource, UICollectionViewDelegate>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end



@interface ZLEditImageViewController (SWIFT_EXTENSION(HHSDKVideo)) <UIScrollViewDelegate>
- (UIView * _Nullable)viewForZoomingInScrollView:(UIScrollView * _Nonnull)scrollView SWIFT_WARN_UNUSED_RESULT;
- (void)scrollViewDidZoom:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndZooming:(UIScrollView * _Nonnull)scrollView withView:(UIView * _Nullable)view atScale:(CGFloat)scale;
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDragging:(UIScrollView * _Nonnull)scrollView willDecelerate:(BOOL)decelerate;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndScrollingAnimation:(UIScrollView * _Nonnull)scrollView;
@end

@class AVAsset;

SWIFT_CLASS("_TtC10HHSDKVideo25ZLEditVideoViewController")
@interface ZLEditVideoViewController : UIViewController
@property (nonatomic, copy) void (^ _Nullable editFinishBlock)(NSURL * _Nullable);
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
/// initialize
/// \param avAsset AVAsset对象，需要传入本地视频，网络视频不支持
///
/// \param animateDismiss 退出界面时是否显示dismiss动画
///
- (nonnull instancetype)initWithAvAsset:(AVAsset * _Nonnull)avAsset animateDismiss:(BOOL)animateDismiss OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLayoutSubviews;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@interface ZLEditVideoViewController (SWIFT_EXTENSION(HHSDKVideo)) <UIGestureRecognizerDelegate>
- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer * _Nonnull)gestureRecognizer SWIFT_WARN_UNUSED_RESULT;
@end

@class UICollectionViewLayout;

@interface ZLEditVideoViewController (SWIFT_EXTENSION(HHSDKVideo)) <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDragging:(UIScrollView * _Nonnull)scrollView willDecelerate:(BOOL)decelerate;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
- (UIEdgeInsets)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout insetForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView willDisplayCell:(UICollectionViewCell * _Nonnull)cell forItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

@class UIEvent;

SWIFT_CLASS("_TtC10HHSDKVideo15ZLEnlargeButton")
@interface ZLEnlargeButton : UIButton
- (BOOL)pointInside:(CGPoint)point withEvent:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

enum ZLFilterType : NSInteger;

SWIFT_CLASS("_TtC10HHSDKVideo8ZLFilter")
@interface ZLFilter : NSObject
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name filterType:(enum ZLFilterType)filterType OBJC_DESIGNATED_INITIALIZER;
/// 可传入 applier 自定义滤镜
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name applier:(UIImage * _Nonnull (^ _Nullable)(UIImage * _Nonnull))applier OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



@interface ZLFilter (SWIFT_EXTENSION(HHSDKVideo))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSArray<ZLFilter *> * _Nonnull all;)
+ (NSArray<ZLFilter *> * _Nonnull)all SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZLFilter * _Nonnull normal;)
+ (ZLFilter * _Nonnull)normal SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZLFilter * _Nonnull clarendon;)
+ (ZLFilter * _Nonnull)clarendon SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZLFilter * _Nonnull nashville;)
+ (ZLFilter * _Nonnull)nashville SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZLFilter * _Nonnull apply1977;)
+ (ZLFilter * _Nonnull)apply1977 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZLFilter * _Nonnull toaster;)
+ (ZLFilter * _Nonnull)toaster SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZLFilter * _Nonnull chrome;)
+ (ZLFilter * _Nonnull)chrome SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZLFilter * _Nonnull fade;)
+ (ZLFilter * _Nonnull)fade SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZLFilter * _Nonnull instant;)
+ (ZLFilter * _Nonnull)instant SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZLFilter * _Nonnull process;)
+ (ZLFilter * _Nonnull)process SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZLFilter * _Nonnull transfer;)
+ (ZLFilter * _Nonnull)transfer SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZLFilter * _Nonnull tone;)
+ (ZLFilter * _Nonnull)tone SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZLFilter * _Nonnull linear;)
+ (ZLFilter * _Nonnull)linear SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZLFilter * _Nonnull sepia;)
+ (ZLFilter * _Nonnull)sepia SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZLFilter * _Nonnull mono;)
+ (ZLFilter * _Nonnull)mono SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZLFilter * _Nonnull noir;)
+ (ZLFilter * _Nonnull)noir SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZLFilter * _Nonnull tonal;)
+ (ZLFilter * _Nonnull)tonal SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, ZLFilterType, open) {
  ZLFilterTypeNormal = 0,
  ZLFilterTypeChrome = 1,
  ZLFilterTypeFade = 2,
  ZLFilterTypeInstant = 3,
  ZLFilterTypeProcess = 4,
  ZLFilterTypeTransfer = 5,
  ZLFilterTypeTone = 6,
  ZLFilterTypeLinear = 7,
  ZLFilterTypeSepia = 8,
  ZLFilterTypeMono = 9,
  ZLFilterTypeNoir = 10,
  ZLFilterTypeTonal = 11,
};


SWIFT_CLASS("_TtC10HHSDKVideo16ZLImageClipRatio")
@interface ZLImageClipRatio : NSObject
- (nonnull instancetype)initWithTitle:(NSString * _Nonnull)title whRatio:(CGFloat)whRatio isCircle:(BOOL)isCircle OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



@interface ZLImageClipRatio (SWIFT_EXTENSION(HHSDKVideo))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZLImageClipRatio * _Nonnull custom;)
+ (ZLImageClipRatio * _Nonnull)custom SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZLImageClipRatio * _Nonnull circle;)
+ (ZLImageClipRatio * _Nonnull)circle SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZLImageClipRatio * _Nonnull wh1x1;)
+ (ZLImageClipRatio * _Nonnull)wh1x1 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZLImageClipRatio * _Nonnull wh3x4;)
+ (ZLImageClipRatio * _Nonnull)wh3x4 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZLImageClipRatio * _Nonnull wh4x3;)
+ (ZLImageClipRatio * _Nonnull)wh4x3 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZLImageClipRatio * _Nonnull wh2x3;)
+ (ZLImageClipRatio * _Nonnull)wh2x3 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZLImageClipRatio * _Nonnull wh3x2;)
+ (ZLImageClipRatio * _Nonnull)wh3x2 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZLImageClipRatio * _Nonnull wh9x16;)
+ (ZLImageClipRatio * _Nonnull)wh9x16 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZLImageClipRatio * _Nonnull wh16x9;)
+ (ZLImageClipRatio * _Nonnull)wh16x9 SWIFT_WARN_UNUSED_RESULT;
@end

enum ZLURLType : NSInteger;

SWIFT_CLASS("_TtC10HHSDKVideo24ZLImagePreviewController")
@interface ZLImagePreviewController : UIViewController
@property (nonatomic, copy) void (^ _Nullable longPressBlock)(ZLImagePreviewController * _Nullable, UIImage * _Nullable, NSInteger);
@property (nonatomic, copy) void (^ _Nullable doneBlock)(NSArray * _Nonnull);
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable videoHttpHeader;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
/// \param datas Must be one of PHAsset, UIImage and URL, will filter others in init function.
///
/// \param showBottomView If showSelectBtn is true, showBottomView is always true.
///
/// \param index Index for first display.
///
/// \param urlType Tell me the url is image or video.
///
/// \param urlImageLoader Called when cell will display, cell will layout after callback when image load finish. The first block is progress callback, second is load finish callback.
///
- (nonnull instancetype)initWithDatas:(NSArray * _Nonnull)datas index:(NSInteger)index showSelectBtn:(BOOL)showSelectBtn showBottomView:(BOOL)showBottomView urlType:(enum ZLURLType (^ _Nullable)(NSURL * _Nonnull))urlType urlImageLoader:(void (^ _Nullable)(NSURL * _Nonnull, UIImageView * _Nonnull, void (^ _Nonnull)(CGFloat), void (^ _Nonnull)(void)))urlImageLoader OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLayoutSubviews;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@interface ZLImagePreviewController (SWIFT_EXTENSION(HHSDKVideo))
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
@end


@interface ZLImagePreviewController (SWIFT_EXTENSION(HHSDKVideo)) <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumInteritemSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UIEdgeInsets)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout insetForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didEndDisplayingCell:(UICollectionViewCell * _Nonnull)cell forItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


/// Provide an image sticker container view that conform to this protocol must be a subclass of UIView
/// 必须是UIView的子类遵循这个协议
SWIFT_PROTOCOL("_TtP10HHSDKVideo31ZLImageStickerContainerDelegate_")
@protocol ZLImageStickerContainerDelegate
@property (nonatomic, copy) void (^ _Nullable selectImageBlock)(UIImage * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable hideBlock)(void);
- (void)showIn:(UIView * _Nonnull)view;
@end


SWIFT_CLASS("_TtC10HHSDKVideo19ZLImageStickerState")
@interface ZLImageStickerState : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ZLLanguageType, open) {
  ZLLanguageTypeSystem = 0,
  ZLLanguageTypeChineseSimplified = 1,
  ZLLanguageTypeChineseTraditional = 2,
  ZLLanguageTypeEnglish = 3,
  ZLLanguageTypeJapanese = 4,
  ZLLanguageTypeFrench = 5,
  ZLLanguageTypeGerman = 6,
  ZLLanguageTypeRussian = 7,
  ZLLanguageTypeVietnamese = 8,
  ZLLanguageTypeKorean = 9,
  ZLLanguageTypeMalay = 10,
  ZLLanguageTypeItalian = 11,
  ZLLanguageTypeIndonesian = 12,
  ZLLanguageTypePortuguese = 13,
  ZLLanguageTypeSpanish = 14,
  ZLLanguageTypeTurkish = 15,
};


SWIFT_CLASS("_TtC10HHSDKVideo12ZLMosaicPath")
@interface ZLMosaicPath : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ZLNoAuthorityType, open) {
  ZLNoAuthorityTypeLibrary = 0,
  ZLNoAuthorityTypeCamera = 1,
  ZLNoAuthorityTypeMicrophone = 2,
};

typedef SWIFT_ENUM(NSInteger, ZLPhotoBrowserStyle, open) {
/// The album list is embedded in the navigation of the thumbnail interface, click the drop-down display.
  ZLPhotoBrowserStyleEmbedAlbumList = 0,
/// The display relationship between the album list and the thumbnail interface is push.
  ZLPhotoBrowserStyleExternalAlbumList = 1,
};

enum HUDStyle : NSInteger;
@class PHAsset;

SWIFT_CLASS("_TtC10HHSDKVideo20ZLPhotoConfiguration")
@interface ZLPhotoConfiguration : NSObject
+ (ZLPhotoConfiguration * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
+ (void)resetConfiguration;
/// Photo sorting method, the preview interface is not affected by this parameter. Defaults to true.
@property (nonatomic) BOOL sortAscending;
/// Anything superior than 1 will enable the multiple selection feature. Defaults to 9.
@property (nonatomic) NSInteger maxSelectCount;
/// A count for video max selection. Defaults to 0.
/// warning:
/// Only valid in mix selection mode. (i.e. allowMixSelect = true)
@property (nonatomic) NSInteger maxVideoSelectCount;
/// A count for video min selection. Defaults to 0.
/// warning:
/// Only valid in mix selection mode. (i.e. allowMixSelect = true)
@property (nonatomic) NSInteger minVideoSelectCount;
/// Whether photos and videos can be selected together. Defaults to true.
/// If set to false, only one video can be selected. Defaults to true.
@property (nonatomic) BOOL allowMixSelect;
/// Preview selection max preview count, if the value is zero, only show <code>Camera</code>, <code>Album</code>, <code>Cancel</code> buttons. Defaults to 20.
@property (nonatomic) NSInteger maxPreviewCount;
@property (nonatomic) CGFloat cellCornerRadio;
/// If set to false, gif and livephoto cannot be selected either. Defaults to true.
@property (nonatomic) BOOL allowSelectImage;
@property (nonatomic) BOOL allowSelectVideo;
/// Allow select Gif, it only controls whether it is displayed in Gif form.
/// If value is false, the Gif logo is not displayed. Defaults to true.
@property (nonatomic) BOOL allowSelectGif;
/// Allow select LivePhoto, it only controls whether it is displayed in LivePhoto form.
/// If value is false, the LivePhoto logo is not displayed. Defaults to false.
@property (nonatomic) BOOL allowSelectLivePhoto;
/// Allow take photos in the album. Defaults to true.
/// warning:
/// If allowTakePhoto and allowRecordVideo are both false, it will not be displayed.
@property (nonatomic) BOOL allowTakePhotoInLibrary;
@property (nonatomic) BOOL allowEditImage;
@property (nonatomic) BOOL allowEditVideo;
/// Control whether to display the selection button animation when selecting. Defaults to true.
@property (nonatomic) BOOL animateSelectBtnWhenSelect;
/// Animation duration for select button
@property (nonatomic) CFTimeInterval selectBtnAnimationDuration;
/// After selecting a image/video in the thumbnail interface, enter the editing interface directly. Defaults to false.
/// <ul>
///   <li>
///     discussion: Editing image is only valid when allowEditImage is true and maxSelectCount is 1.
///     Editing video is only valid when allowEditVideo is true and maxSelectCount is 1.
///   </li>
/// </ul>
@property (nonatomic) BOOL editAfterSelectThumbnailImage;
/// Only valid when allowMixSelect is false and allowEditVideo is true. Defaults to true.
/// Just like the Wechat-Timeline selection style. If you want to crop the video after select thumbnail under allowMixSelect = true, please use <em>editAfterSelectThumbnailImage</em>.
@property (nonatomic) BOOL cropVideoAfterSelectThumbnail;
/// If image edit tools only has clip and this property is true. When you click edit, the cropping interface (i.e. ZLClipImageViewController) will be displayed. Defaults to false.
@property (nonatomic) BOOL showClipDirectlyIfOnlyHasClipTool;
/// Save the edited image to the album after editing. Defaults to true.
@property (nonatomic) BOOL saveNewImageAfterEdit;
/// If true, you can slide select photos in album. Defaults to true.
@property (nonatomic) BOOL allowSlideSelect;
/// When slide select is active, will auto scroll to top or bottom when your finger at the top or bottom. Defaults to true.
@property (nonatomic) BOOL autoScrollWhenSlideSelectIsActive;
/// The max speed (pt/s) of auto scroll. Defaults to 600.
@property (nonatomic) CGFloat autoScrollMaxSpeed;
/// If true, you can drag select photo when preview selection style. Defaults to false.
@property (nonatomic) BOOL allowDragSelect;
/// Allow select full image. Defaults to true.
@property (nonatomic) BOOL allowSelectOriginal;
/// Allow access to the preview large image interface (That is, whether to allow access to the large image interface after clicking the thumbnail image). Defaults to true.
@property (nonatomic) BOOL allowPreviewPhotos;
/// Whether to show the preview button (i.e. the preview button in the lower left corner of the thumbnail interface). Defaults to true.
@property (nonatomic) BOOL showPreviewButtonInAlbum;
/// Whether to display the selected count on the button. Defaults to true.
@property (nonatomic) BOOL showSelectCountOnDoneBtn;
/// The column count when iPhone is in portait mode. Minimum is 2, maximum is 6. Defaults to 4.
/// \code
/// iPhone landscape mode: columnCount += 2.
/// iPad portait mode: columnCount += 2.
/// iPad landscape mode: columnCount += 4.
///
/// \endcode
@property (nonatomic) NSInteger columnCount;
/// Maximum cropping time when editing video, unit: second. Defaults to 10.
@property (nonatomic) NSInteger maxEditVideoTime;
/// Allow to choose the maximum duration of the video. Defaults to 120.
@property (nonatomic) NSInteger maxSelectVideoDuration;
/// Allow to choose the minimum duration of the video. Defaults to 0.
@property (nonatomic) NSInteger minSelectVideoDuration;
/// Image editor configuration.
@property (nonatomic, strong) ZLEditImageConfiguration * _Nonnull editImageConfiguration;
/// Show the image captured by the camera is displayed on the camera button inside the album. Defaults to false.
@property (nonatomic) BOOL showCaptureImageOnTakePhotoBtn;
/// In single selection mode, whether to display the selection button. Defaults to false.
@property (nonatomic) BOOL showSelectBtnWhenSingleSelect;
/// Overlay a mask layer on top of the selected photos. Defaults to true.
@property (nonatomic) BOOL showSelectedMask;
/// Display a border on the selected photos cell. Defaults to false.
@property (nonatomic) BOOL showSelectedBorder;
/// Overlay a mask layer above the cells that cannot be selected. Defaults to true.
@property (nonatomic) BOOL showInvalidMask;
/// Display the index of the selected photos. Defaults to true.
@property (nonatomic) BOOL showSelectedIndex;
/// Display the selected photos at the bottom of the preview large photos interface. Defaults to true.
@property (nonatomic) BOOL showSelectedPhotoPreview;
/// Allow framework fetch photos when callback. Defaults to true.
@property (nonatomic) BOOL shouldAnialysisAsset;
/// Timeout for image parsing. Defaults to 20.
@property (nonatomic) NSTimeInterval timeout;
/// Language for framework.
@property (nonatomic) enum ZLLanguageType languageType;
/// Whether to use custom camera. Defaults to true.
@property (nonatomic) BOOL useCustomCamera;
/// Allow taking photos in the camera (Need allowSelectImage to be true). Defaults to true.
@property (nonatomic) BOOL allowTakePhoto;
/// Allow recording in the camera (Need allowSelectVideo to be true). Defaults to true.
@property (nonatomic) BOOL allowRecordVideo;
/// Minimum recording duration. Defaults to 0.
@property (nonatomic) NSInteger minRecordDuration;
/// Maximum recording duration. Defaults to 10, minimum is 1.
@property (nonatomic) NSInteger maxRecordDuration;
/// The configuration for camera.
@property (nonatomic, strong) ZLCameraConfiguration * _Nonnull cameraConfiguration;
/// Hud style. Defaults to lightBlur.
@property (nonatomic) enum HUDStyle hudStyle;
/// This block will be called before selecting an image, the developer can first determine whether the asset is allowed to be selected.
/// Only control whether it is allowed to be selected, and will not affect the selection logic in the framework.
/// <ul>
///   <li>
///     Tips: If the choice is not allowed, the developer can toast prompt the user for relevant information.
///   </li>
/// </ul>
@property (nonatomic, copy) BOOL (^ _Nullable canSelectAsset)(PHAsset * _Nonnull);
/// If user choose limited Photo mode, a button with ‘+’ will be added to the ZLThumbnailViewController. It will call PHPhotoLibrary.shared().presentLimitedLibraryPicker(from:) to add photo. Defaults to true.
/// E.g., Sina Weibo’s ImagePicker
@property (nonatomic) BOOL showAddPhotoButton;
/// iOS14 limited Photo mode, will show collection footer view in ZLThumbnailViewController.
/// Will go to system setting if clicked. Defaults to true.
@property (nonatomic) BOOL showEnterSettingTips;
/// Callback after the no authority alert dismiss.
@property (nonatomic, copy) void (^ _Nullable noAuthorityCallback)(enum ZLNoAuthorityType);
/// Allow user to do something before select photo result callback.
/// And you must call the second parameter of this block to continue the photos selection.
/// The first parameter is the current controller.
/// The second parameter is the block that needs to be called after the user completes the operation.
@property (nonatomic, copy) void (^ _Nullable operateBeforeDoneAction)(UIViewController * _Nonnull, void (^ _Nonnull)(void));
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface ZLPhotoConfiguration (SWIFT_EXTENSION(HHSDKVideo))
- (ZLPhotoConfiguration * _Nonnull)allowSelectVideo:(BOOL)value;
- (ZLPhotoConfiguration * _Nonnull)canSelectAsset:(BOOL (^ _Nullable)(PHAsset * _Nonnull))block;
- (ZLPhotoConfiguration * _Nonnull)showAddPhotoButton:(BOOL)value;
- (ZLPhotoConfiguration * _Nonnull)showEnterSettingTips:(BOOL)value;
- (ZLPhotoConfiguration * _Nonnull)noAuthorityCallback:(void (^ _Nullable)(enum ZLNoAuthorityType))callback;
- (ZLPhotoConfiguration * _Nonnull)operateBeforeDoneAction:(void (^ _Nullable)(UIViewController * _Nonnull, void (^ _Nonnull)(void)))block;
@end

@class ZLPhotoModel;
@class NSData;
@class PHLivePhoto;
@class AVPlayerItem;

SWIFT_CLASS("_TtC10HHSDKVideo14ZLPhotoManager")
@interface ZLPhotoManager : NSObject
/// Save image to album.
+ (void)saveImageToAlbumWithImage:(UIImage * _Nonnull)image completion:(void (^ _Nullable)(BOOL, PHAsset * _Nullable))completion;
/// Save video to album.
+ (void)saveVideoToAlbumWithUrl:(NSURL * _Nonnull)url completion:(void (^ _Nullable)(BOOL, PHAsset * _Nullable))completion;
/// Fetch photos from result.
+ (NSArray<ZLPhotoModel *> * _Nonnull)fetchPhotoIn:(PHFetchResult<PHAsset *> * _Nonnull)result ascending:(BOOL)ascending allowSelectImage:(BOOL)allowSelectImage allowSelectVideo:(BOOL)allowSelectVideo limitCount:(NSInteger)limitCount SWIFT_WARN_UNUSED_RESULT;
/// Fetch all album list.
+ (void)getPhotoAlbumListWithAscending:(BOOL)ascending allowSelectImage:(BOOL)allowSelectImage allowSelectVideo:(BOOL)allowSelectVideo completion:(SWIFT_NOESCAPE void (^ _Nonnull)(NSArray<ZLAlbumListModel *> * _Nonnull))completion;
/// Fetch camera roll album.
+ (void)getCameraRollAlbumWithAllowSelectImage:(BOOL)allowSelectImage allowSelectVideo:(BOOL)allowSelectVideo completion:(void (^ _Nonnull)(ZLAlbumListModel * _Nonnull))completion;
+ (PHImageRequestID)fetchImageFor:(PHAsset * _Nonnull)asset size:(CGSize)size progress:(void (^ _Nullable)(CGFloat, NSError * _Nullable, BOOL * _Nonnull, NSDictionary * _Nullable))progress completion:(void (^ _Nonnull)(UIImage * _Nullable, BOOL))completion;
+ (PHImageRequestID)fetchOriginalImageFor:(PHAsset * _Nonnull)asset progress:(void (^ _Nullable)(CGFloat, NSError * _Nullable, BOOL * _Nonnull, NSDictionary * _Nullable))progress completion:(void (^ _Nonnull)(UIImage * _Nullable, BOOL))completion;
/// Fetch asset data.
+ (PHImageRequestID)fetchOriginalImageDataFor:(PHAsset * _Nonnull)asset progress:(void (^ _Nullable)(CGFloat, NSError * _Nullable, BOOL * _Nonnull, NSDictionary * _Nullable))progress completion:(void (^ _Nonnull)(NSData * _Nonnull, NSDictionary * _Nullable, BOOL))completion;
+ (PHImageRequestID)fetchLivePhotoFor:(PHAsset * _Nonnull)asset completion:(void (^ _Nonnull)(PHLivePhoto * _Nullable, NSDictionary * _Nullable, BOOL))completion SWIFT_WARN_UNUSED_RESULT;
+ (PHImageRequestID)fetchVideoFor:(PHAsset * _Nonnull)asset progress:(void (^ _Nullable)(CGFloat, NSError * _Nullable, BOOL * _Nonnull, NSDictionary * _Nullable))progress completion:(void (^ _Nonnull)(AVPlayerItem * _Nullable, NSDictionary * _Nullable, BOOL))completion SWIFT_WARN_UNUSED_RESULT;
+ (PHImageRequestID)fetchAVAssetForVideo:(PHAsset * _Nonnull)asset completion:(void (^ _Nonnull)(AVAsset * _Nullable, NSDictionary * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
/// Fetch asset local file path.
+ (void)fetchAssetFilePathWithAsset:(PHAsset * _Nonnull)asset completion:(void (^ _Nonnull)(NSString * _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface ZLPhotoManager (SWIFT_EXTENSION(HHSDKVideo))
+ (BOOL)hasPhotoLibratyAuthority SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)hasCameraAuthority SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)hasMicrophoneAuthority SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC10HHSDKVideo12ZLPhotoModel")
@interface ZLPhotoModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




SWIFT_CLASS("_TtC10HHSDKVideo19ZLPhotoPreviewSheet")
@interface ZLPhotoPreviewSheet : UIView
/// Success callback
/// block params
/// <ul>
///   <li>
///     params1: images for asset.
///   </li>
///   <li>
///     params2: selected assets
///   </li>
///   <li>
///     params3: is full image
///   </li>
/// </ul>
@property (nonatomic, copy) void (^ _Nullable selectImageBlock)(NSArray<HHPhotoPickerModel *> * _Nonnull, BOOL);
/// Callback for photos that failed to parse
/// block params
/// <ul>
///   <li>
///     params1: failed assets.
///   </li>
///   <li>
///     params2: index for asset
///   </li>
/// </ul>
@property (nonatomic, copy) void (^ _Nullable selectImageRequestErrorBlock)(NSArray<PHAsset *> * _Nonnull, NSArray<NSNumber *> * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable cancelBlock)(void);
- (nonnull instancetype)initWithFrame:(CGRect)frame;
/// \param selectedAssets preselected assets
///
- (nonnull instancetype)initWithSelectedAssets:(NSArray<PHAsset *> * _Nullable)selectedAssets OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (void)showPreviewWithAnimate:(BOOL)animate sender:(UIViewController * _Nonnull)sender;
- (void)showPhotoLibraryWithSender:(UIViewController * _Nonnull)sender;
/// 传入已选择的assets，并预览
- (void)previewAssetsWithSender:(UIViewController * _Nonnull)sender assets:(NSArray<PHAsset *> * _Nonnull)assets index:(NSInteger)index isOriginal:(BOOL)isOriginal showBottomViewAndSelectBtn:(BOOL)showBottomViewAndSelectBtn;
@end


@interface ZLPhotoPreviewSheet (SWIFT_EXTENSION(HHSDKVideo)) <UIGestureRecognizerDelegate>
- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer * _Nonnull)gestureRecognizer SWIFT_WARN_UNUSED_RESULT;
@end

@class PHChange;

@interface ZLPhotoPreviewSheet (SWIFT_EXTENSION(HHSDKVideo)) <PHPhotoLibraryChangeObserver>
- (void)photoLibraryDidChange:(PHChange * _Nonnull)changeInstance;
@end

@class UIImagePickerController;

@interface ZLPhotoPreviewSheet (SWIFT_EXTENSION(HHSDKVideo)) <UIImagePickerControllerDelegate, UINavigationControllerDelegate>
- (void)imagePickerController:(UIImagePickerController * _Nonnull)picker didFinishPickingMediaWithInfo:(NSDictionary<UIImagePickerControllerInfoKey, id> * _Nonnull)info;
@end


@interface ZLPhotoPreviewSheet (SWIFT_EXTENSION(HHSDKVideo)) <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView willDisplayCell:(UICollectionViewCell * _Nonnull)cell forItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

enum CancelButtonStyle : NSInteger;
@class UIBlurEffect;

/// Custom UI configuration (include colors, images, text, font)
SWIFT_CLASS("_TtC10HHSDKVideo22ZLPhotoUIConfiguration")
@interface ZLPhotoUIConfiguration : NSObject
+ (ZLPhotoUIConfiguration * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
+ (void)resetConfiguration;
@property (nonatomic) enum ZLPhotoBrowserStyle style;
@property (nonatomic) UIStatusBarStyle statusBarStyle;
/// text: Cancel.  image: ‘x’. Default to image.
@property (nonatomic) enum CancelButtonStyle navCancelButtonStyle;
/// Whether to show the status bar when previewing photos. Defaults to false.
@property (nonatomic) BOOL showStatusBarInPreviewInterface;
/// The blur effect of the navigation bar in the album list
@property (nonatomic, strong) UIBlurEffect * _Nullable navViewBlurEffectOfAlbumList;
/// The blur effect of the navigation bar in the preview interface
@property (nonatomic, strong) UIBlurEffect * _Nullable navViewBlurEffectOfPreview;
/// The blur effect of the bottom tool bar in the album list
@property (nonatomic, strong) UIBlurEffect * _Nullable bottomViewBlurEffectOfAlbumList;
/// The blur effect of the bottom tool bar in the preview interface
@property (nonatomic, strong) UIBlurEffect * _Nullable bottomViewBlurEffectOfPreview;
/// Developers can customize images, but the name of the custom image resource must be consistent with the image name in the replaced bundle.
/// <ul>
///   <li>
///     example: Developers need to replace the selected and unselected image resources, and the array that needs to be passed in is
///     [“zl_btn_selected”, “zl_btn_unselected”].
///   </li>
/// </ul>
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull customImageNames;
/// Developers can customize images, but the name of the custom image resource must be consistent with the image name in the replaced bundle.
/// <ul>
///   <li>
///     example: Developers need to replace the selected and unselected image resources, and the array that needs to be passed in is
///     [“zl_btn_selected”: selectedImage, “zl_btn_unselected”: unselectedImage].
///   </li>
/// </ul>
@property (nonatomic, copy) NSDictionary<NSString *, UIImage *> * _Nonnull customImageForKey_objc;
/// Developers can customize languages (This property is only for objc).
/// warning:
/// Please pay attention to the placeholders contained in languages when changing, such as %ld, %@.
/// <ul>
///   <li>
///     example: If you needs to replace
///     key: @“loading”, value: @“loading, waiting please” language,
///     The dictionary that needs to be passed in is @[@“loading”: @“text to be replaced”].
///   </li>
/// </ul>
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nonnull customLanguageKeyValue_objc;
/// Font name.
@property (nonatomic, copy) NSString * _Nullable themeFontName;
/// Preview selection mode, translucent background color above.
/// 预览快速选择模式下，上方透明区域背景色
@property (nonatomic, strong) UIColor * _Nonnull sheetTranslucentColor;
/// Preview selection mode, a background color for <code>Camera</code>, <code>Album</code>, <code>Cancel</code> buttons.
/// 预览快速选择模式下，按钮背景颜色
@property (nonatomic, strong) UIColor * _Nonnull sheetBtnBgColor;
/// Preview selection mode, a text color for <code>Camera</code>, <code>Album</code>, <code>Cancel</code> buttons.
/// 预览快速选择模式下，按钮标题颜色
@property (nonatomic, strong) UIColor * _Nonnull sheetBtnTitleColor;
/// Preview selection mode, cancel button title color when the selection amount is superior than 0.
/// 预览快速选择模式下，按钮标题高亮颜色
@property (nonatomic, strong) UIColor * _Nonnull sheetBtnTitleTintColor;
/// A color for navigation bar.
/// 相册列表及小图界面导航条背景色
@property (nonatomic, strong) UIColor * _Nonnull navBarColor;
/// A color for navigation bar in preview interface.
/// 预览大图界面的导航条背景色
@property (nonatomic, strong) UIColor * _Nonnull navBarColorOfPreviewVC;
/// A color for Navigation bar text.
/// 相册列表及小图界面导航栏标题颜色
@property (nonatomic, strong) UIColor * _Nonnull navTitleColor;
/// A color for Navigation bar text of preview vc.
/// 预览大图界面导航栏标题颜色
@property (nonatomic, strong) UIColor * _Nonnull navTitleColorOfPreviewVC;
/// The background color of the title view when the frame style is embedAlbumList.
/// 下拉选择相册列表模式下，选择区域的背景色
@property (nonatomic, strong) UIColor * _Nonnull navEmbedTitleViewBgColor;
/// A color for background in album list.
/// 相册列表背景色
@property (nonatomic, strong) UIColor * _Nonnull albumListBgColor;
/// A color of the translucent area below the embed album list.
/// 嵌入式相册列表下方透明区域颜色
@property (nonatomic, strong) UIColor * _Nonnull embedAlbumListTranslucentColor;
/// A color for album list title label.
/// 相册列表标题颜色
@property (nonatomic, strong) UIColor * _Nonnull albumListTitleColor;
/// A color for album list count label.
/// 相册列表数量label的颜色
@property (nonatomic, strong) UIColor * _Nonnull albumListCountColor;
/// A color for album list separator.
/// 相册列表分割线颜色
@property (nonatomic, strong) UIColor * _Nonnull separatorColor;
/// A color for background in thumbnail interface.
/// 相册小图界面背景色
@property (nonatomic, strong) UIColor * _Nonnull thumbnailBgColor;
/// A color for background in preview interface..
/// 预览大图界面背景色
@property (nonatomic, strong) UIColor * _Nonnull previewVCBgColor;
/// A color for background in bottom tool view.
/// 相册小图界面底部工具条背景色
@property (nonatomic, strong) UIColor * _Nonnull bottomToolViewBgColor;
/// A color for background in bottom tool view in preview interface.
/// 预览大图界面底部工具条背景色
@property (nonatomic, strong) UIColor * _Nonnull bottomToolViewBgColorOfPreviewVC;
/// The normal state title color of bottom tool view buttons. Without done button.
/// 相册小图界面底部按钮可交互状态下标题颜色，不包括 <code>完成</code> 按钮
@property (nonatomic, strong) UIColor * _Nonnull bottomToolViewBtnNormalTitleColor;
/// The normal state title color of bottom tool view done button.
/// 相册小图界面底部 <code>完成</code> 按钮可交互状态下标题颜色
@property (nonatomic, strong) UIColor * _Nonnull bottomToolViewDoneBtnNormalTitleColor;
/// The normal state title color of bottom tool view buttons in preview interface.  Without done button.
/// 预览大图界面底部按钮可交互状态下标题颜色，不包括 <code>完成</code> 按钮
@property (nonatomic, strong) UIColor * _Nonnull bottomToolViewBtnNormalTitleColorOfPreviewVC;
/// The normal state title color of bottom tool view done button.
/// 预览大图界面底部 <code>完成</code> 按钮可交互状态下标题颜色
@property (nonatomic, strong) UIColor * _Nonnull bottomToolViewDoneBtnNormalTitleColorOfPreviewVC;
/// The disable state title color of bottom tool view buttons.  Without done button.
/// 相册小图界面底部按钮不可交互状态下标题颜色，不包括 <code>完成</code> 按钮
@property (nonatomic, strong) UIColor * _Nonnull bottomToolViewBtnDisableTitleColor;
/// The disable state title color of bottom tool view done button.
/// 相册小图界面底部 <code>完成</code> 按钮不可交互状态下标题颜色
@property (nonatomic, strong) UIColor * _Nonnull bottomToolViewDoneBtnDisableTitleColor;
/// The disable state title color of bottom tool view buttons in preview interface.  Without done button.
/// 预览大图界面底部按钮不可交互状态下标题颜色，不包括 <code>完成</code> 按钮
@property (nonatomic, strong) UIColor * _Nonnull bottomToolViewBtnDisableTitleColorOfPreviewVC;
/// The disable state title color of bottom tool view done button  in preview interface.
/// 预览大图界面底部 <code>完成</code> 按钮不可交互状态下标题颜色
@property (nonatomic, strong) UIColor * _Nonnull bottomToolViewDoneBtnDisableTitleColorOfPreviewVC;
/// The normal state background color of bottom tool view buttons.
/// 相册小图界面底部按钮可交互状态下背景色
@property (nonatomic, strong) UIColor * _Nonnull bottomToolViewBtnNormalBgColor;
/// The normal state background color of bottom tool view buttons in preview interface.
/// 预览大图界面底部按钮可交互状态下背景色
@property (nonatomic, strong) UIColor * _Nonnull bottomToolViewBtnNormalBgColorOfPreviewVC;
/// The disable state background color of bottom tool view buttons.
/// 相册小图界面底部按钮不可交互状态下背景色
@property (nonatomic, strong) UIColor * _Nonnull bottomToolViewBtnDisableBgColor;
/// The disable state background color of bottom tool view buttons in preview interface.
/// 预览大图界面底部按钮不可交互状态下背景色
@property (nonatomic, strong) UIColor * _Nonnull bottomToolViewBtnDisableBgColorOfPreviewVC;
/// With iOS14 limited authority, a color for select more photos at the bottom of the thumbnail interface.
/// iOS14 limited权限下，下方提示选择更多图片信息文字的颜色
@property (nonatomic, strong) UIColor * _Nonnull selectMorePhotoWhenAuthIsLismitedTitleColor;
/// The record progress color of custom camera.
/// 自定义相机录制视频时进度条颜色
@property (nonatomic, strong) UIColor * _Nonnull cameraRecodeProgressColor;
/// Mask layer color of selected cell.
/// 已选择照片上方遮罩阴影颜色
@property (nonatomic, strong) UIColor * _Nonnull selectedMaskColor;
/// Border color of selected cell.
/// 已选择照片border颜色
@property (nonatomic, strong) UIColor * _Nonnull selectedBorderColor;
/// Mask layer color of the cell that cannot be selected.
/// 不可选的照片上方遮罩阴影颜色
@property (nonatomic, strong) UIColor * _Nonnull invalidMaskColor;
/// The text color of selected cell index label.
/// 已选照片右上角序号label背景色
@property (nonatomic, strong) UIColor * _Nonnull indexLabelTextColor;
/// The background color of selected cell index label.
/// 已选照片右上角序号label背景色
@property (nonatomic, strong) UIColor * _Nonnull indexLabelBgColor;
/// The background color of camera cell inside album.
/// 相册小图界面拍照按钮背景色
@property (nonatomic, strong) UIColor * _Nonnull cameraCellBgColor;
/// The normal color of adjust slider.
/// 编辑图片，调整饱和度、对比度、亮度时，右侧slider背景色
@property (nonatomic, strong) UIColor * _Nonnull adjustSliderNormalColor;
/// The tint color of adjust slider.
/// 编辑图片，调整饱和度、对比度、亮度时，右侧slider背景高亮色
@property (nonatomic, strong) UIColor * _Nonnull adjustSliderTintColor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, CancelButtonStyle, open) {
  CancelButtonStyleText = 0,
  CancelButtonStyleImage = 1,
};



SWIFT_CLASS("_TtC10HHSDKVideo13ZLProgressHUD")
@interface ZLProgressHUD : UIView
- (nonnull instancetype)initWithStyle:(enum HUDStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)showWithTimeout:(NSTimeInterval)timeout;
- (void)hide;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM(NSInteger, HUDStyle, open) {
  HUDStyleLight = 0,
  HUDStyleLightBlur = 1,
  HUDStyleDark = 2,
  HUDStyleDarkBlur = 3,
};


SWIFT_CLASS("_TtC10HHSDKVideo18ZLTextStickerState")
@interface ZLTextStickerState : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ZLURLType, open) {
  ZLURLTypeImage = 0,
  ZLURLTypeVideo = 1,
};


SWIFT_CLASS("_TtC10HHSDKVideo14ZLVideoManager")
@interface ZLVideoManager : NSObject
/// 没有针对不同分辨率视频做处理，仅用于处理相机拍照的视频
+ (void)mergeVideosWithFileUrls:(NSArray<NSURL *> * _Nonnull)fileUrls completion:(void (^ _Nonnull)(NSURL * _Nullable, NSError * _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface ZLVideoManager (SWIFT_EXTENSION(HHSDKVideo))
@end

typedef SWIFT_ENUM(NSInteger, ExportType, open) {
  ExportTypeMov = 0,
  ExportTypeMp4 = 1,
};


@interface ZLVideoManager (SWIFT_EXTENSION(HHSDKVideo))
+ (void)exportVideoFor:(PHAsset * _Nonnull)asset exportType:(enum ExportType)exportType presetName:(NSString * _Nonnull)presetName complete:(void (^ _Nonnull)(NSURL * _Nullable, NSError * _Nullable))complete;
+ (void)exportVideoFor:(AVAsset * _Nonnull)asset range:(CMTimeRange)range exportType:(enum ExportType)exportType presetName:(NSString * _Nonnull)presetName complete:(void (^ _Nonnull)(NSURL * _Nullable, NSError * _Nullable))complete;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif
